### ISSUE TITLE
local install meteor 1.8.2 on Debian Buster

### ISSUE THREAD

**Issue by CableGuy67** [Shelagh-Lewins/twisted-threads-2#1]
In order to get things running I first tried with the master branch after cloning the repo locally. I needed to run the following to get a running app.

`meteor npm install --save @babel/runtime react react-dom react-router-dom react-redux redux redux-thunk redux-logger updeep redux-devtools redux-devtools-log-monitor redux-devtools-dock-monitor redux-devtools-inspector prop-types reactstrap formik react-paginate query-string bootstrap`
and also,
`meteor npm install --save sinon`

Then I checked out the development branch locally and had to add the following.

`meteor npm install --save @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome reselect tinycolor2 react-color save-svg-as-png jimp`

After that, the development version was up and running. 

I'm not a node wiz, but I guess these need to be added to the package lists so they are caught with the `npm install` bit?

**Comment by Shelagh-Lewins** [comment]
That's interesting. Those packages are listed under dependencies in package.json. I wonder if it is this issue: https://github.com/npm/npm/issues/17282

If so, deleting package_lock.json and rerunning npm install might fix it?

**Comment by CableGuy67** [comment]
Yeah, not sure why I had all the issues the first time. I deleted the old stuff entirely.

- forked your repo
- cloned my fork via ssh
- added your repo via git as upstream
- checkout the development branch
- npm install
- meteor
All worked straight off this time. The only thing I get now is a note saying that I should use the native bcrypt by running `meteor npm install --save bcrypt` at the root.

So problem solved.

**Comment by Shelagh-Lewins** [comment]
I've merged Development to Master. The bcrypt thing pops up from time to time, see here: https://github.com/meteor/meteor/issues/7773

Glad it's all working!
