### ISSUE TITLE
clicking a tag deletes it

### ISSUE THREAD

**Issue by CableGuy67** [Shelagh-Lewins/twisted-threads-2#4]
When adding new tags if you click on an existing tag it will be automatically deleted. This is due to the component being used.

Expected behavior would be to either have the 'X' be the only part clickable to delete the tag.
Or, to have a confirmation that you really do want to delete the tag.

**Comment by Shelagh-Lewins** [comment]
I've raised an issue on the component:

https://github.com/i-like-robots/react-tags/issues/197

**Comment by Shelagh-Lewins** [comment]
Fixed - it turns out you can write a custom component for the tag and so have a separate button.
